export const REGIONS_WOMEN = [
  "Fort Worth 1",
  "Sacramento 4",
  "Sacramento 2",
  "Fort Worth 3",
];

export const TEAMS_WOMEN = [
  [1, "Fort Worth 1", "UConn", "connecticut"],
  [16, "Fort Worth 1", "UTSA", "utsa"],
  [8, "Fort Worth 1", "Iowa State", "iowa-state"],
  [9, "Fort Worth 1", "Syracuse", "syracuse"],
  [5, "Fort Worth 1", "Maryland", "maryland"],
  [12, "Fort Worth 1", "Murray State", "murray-state"],
  [4, "Fort Worth 1", "North Carolina", "north-carolina"],
  [13, "Fort Worth 1", "Western Illinois", "western-illinois"],
  [6, "Fort Worth 1", "Notre Dame", "notre-dame"],
  [11, "Fort Worth 1", "Fairfield", "fairfield"],
  [3, "Fort Worth 1", "Ohio State", "ohio-state"],
  [14, "Fort Worth 1", "Howard", "howard"],
  [7, "Fort Worth 1", "Illinois", "illinois"],
  [10, "Fort Worth 1", "Colorado", "colorado"],
  [2, "Fort Worth 1", "Vanderbilt", "vanderbilt"],
  [15, "Fort Worth 1", "High Point", "high-point"],
  [1, "Sacramento 4", "South Carolina", "south-carolina"],
  [16, "Sacramento 4", "Southern", "southern"],
  [8, "Sacramento 4", "Clemson", "clemson"],
  [9, "Sacramento 4", "USC", "usc"],
  [5, "Sacramento 4", "Michigan State", "michigan-state"],
  [12, "Sacramento 4", "Colorado State", "colorado-state"],
  [4, "Sacramento 4", "Oklahoma", "oklahoma"],
  [13, "Sacramento 4", "Idaho", "idaho"],
  [6, "Sacramento 4", "Washington", "washington"],
  [11, "Sacramento 4", "South Dakota State", "south-dakota-state"],
  [3, "Sacramento 4", "TCU", "texas-christian"],
  [14, "Sacramento 4", "UC San Diego", "uc-san-diego"],
  [7, "Sacramento 4", "Georgia", "georgia"],
  [10, "Sacramento 4", "Virginia", "virginia"],
  [2, "Sacramento 4", "Iowa", "iowa"],
  [15, "Sacramento 4", "Fairleigh Dickinson", "fairleigh-dickinson"],
  [1, "Sacramento 2", "UCLA", "ucla"],
  [16, "Sacramento 2", "California Baptist", "california-baptist"],
  [8, "Sacramento 2", "Oklahoma State", "oklahoma-state"],
  [9, "Sacramento 2", "Princeton", "princeton"],
  [5, "Sacramento 2", "Ole Miss", "ole-miss"],
  [12, "Sacramento 2", "Gonzaga", "gonzaga"],
  [4, "Sacramento 2", "Minnesota", "minnesota"],
  [13, "Sacramento 2", "Green Bay", "green-bay"],
  [6, "Sacramento 2", "Baylor", "baylor"],
  [11, "Sacramento 2", "Nebraska", "nebraska"],
  [3, "Sacramento 2", "Duke", "duke"],
  [14, "Sacramento 2", "Charleston", "charleston"],
  [7, "Sacramento 2", "Texas Tech", "texas-tech"],
  [10, "Sacramento 2", "Villanova", "villanova"],
  [2, "Sacramento 2", "LSU", "lsu"],
  [15, "Sacramento 2", "Jacksonville", "jacksonville"],
  [1, "Fort Worth 3", "Texas", "texas"],
  [16, "Fort Worth 3", "Missouri State", "missouri-state"],
  [8, "Fort Worth 3", "Oregon", "oregon"],
  [9, "Fort Worth 3", "Virginia Tech", "virginia-tech"],
  [5, "Fort Worth 3", "Kentucky", "kentucky"],
  [12, "Fort Worth 3", "James Madison", "james-madison"],
  [4, "Fort Worth 3", "West Virginia", "west-virginia"],
  [13, "Fort Worth 3", "Miami (OH)", "miami-oh"],
  [6, "Fort Worth 3", "Alabama", "alabama"],
  [11, "Fort Worth 3", "Rhode Island", "rhode-island"],
  [3, "Fort Worth 3", "Louisville", "louisville"],
  [14, "Fort Worth 3", "Vermont", "vermont"],
  [7, "Fort Worth 3", "NC State", "north-carolina-state"],
  [10, "Fort Worth 3", "Tennessee", "tennessee"],
  [2, "Fort Worth 3", "Michigan", "michigan"],
  [15, "Fort Worth 3", "Holy Cross", "holy-cross"],
];
